// This file is auto-generated by: pnpm supabase gen types typescript --local > types/supabase.ts
// Run that command after applying the migration to regenerate.
// The placeholder below allows TypeScript to compile before the schema is applied.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      families: {
        Row: { id: string; parent_name: string; parent_email: string; created_at: string }
        Insert: { id?: string; parent_name: string; parent_email: string; created_at?: string }
        Update: { id?: string; parent_name?: string; parent_email?: string; created_at?: string }
        Relationships: []
      }
      students: {
        Row: { id: string; family_id: string; name: string; active: boolean }
        Insert: { id?: string; family_id: string; name: string; active?: boolean }
        Update: { id?: string; family_id?: string; name?: string; active?: boolean }
        Relationships: [
          { foreignKeyName: 'students_family_id_fkey'; columns: ['family_id']; referencedRelation: 'families'; referencedColumns: ['id'] }
        ]
      }
      availability_template: {
        Row: { id: string; weekday: number; start_time: string; end_time: string }
        Insert: { id?: string; weekday: number; start_time: string; end_time: string }
        Update: { id?: string; weekday?: number; start_time?: string; end_time?: string }
        Relationships: []
      }
      blackouts: {
        Row: { id: string; start_date: string; end_date: string; reason: string | null }
        Insert: { id?: string; start_date: string; end_date: string; reason?: string | null }
        Update: { id?: string; start_date?: string; end_date?: string; reason?: string | null }
        Relationships: []
      }
      recurring_assignments: {
        Row: {
          id: string
          student_id: string
          weekday: number
          start_time: string
          duration_minutes: number
          active_from: string
          active_until: string | null
        }
        Insert: {
          id?: string
          student_id: string
          weekday: number
          start_time: string
          duration_minutes?: number
          active_from: string
          active_until?: string | null
        }
        Update: {
          id?: string
          student_id?: string
          weekday?: number
          start_time?: string
          duration_minutes?: number
          active_from?: string
          active_until?: string | null
        }
        Relationships: [
          { foreignKeyName: 'recurring_assignments_student_id_fkey'; columns: ['student_id']; referencedRelation: 'students'; referencedColumns: ['id'] }
        ]
      }
      lessons: {
        Row: {
          id: string
          student_id: string
          scheduled_at: string
          duration_minutes: number
          status: 'scheduled' | 'cancelled' | 'rescheduled' | 'completed'
          note: string | null
          parent_lesson_id: string | null
          late_cancel: boolean
          created_at: string
        }
        Insert: {
          id?: string
          student_id: string
          scheduled_at: string
          duration_minutes?: number
          status?: 'scheduled' | 'cancelled' | 'rescheduled' | 'completed'
          note?: string | null
          parent_lesson_id?: string | null
          late_cancel?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          student_id?: string
          scheduled_at?: string
          duration_minutes?: number
          status?: 'scheduled' | 'cancelled' | 'rescheduled' | 'completed'
          note?: string | null
          parent_lesson_id?: string | null
          late_cancel?: boolean
          created_at?: string
        }
        Relationships: [
          { foreignKeyName: 'lessons_student_id_fkey'; columns: ['student_id']; referencedRelation: 'students'; referencedColumns: ['id'] }
        ]
      }
      teacher_settings: {
        Row: { id: number; ical_token: string; teacher_uid: string | null }
        Insert: { id?: number; ical_token?: string; teacher_uid?: string | null }
        Update: { id?: number; ical_token?: string; teacher_uid?: string | null }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      lesson_status: 'scheduled' | 'cancelled' | 'rescheduled' | 'completed'
    }
    CompositeTypes: Record<string, never>
  }
}
